export const GET_DEVICE_DATA = 'GET_DEVICE_DATA';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';

export const GET_RANKING_DATA = 'GET_RANKING_DATA';
export const GET_RANKING_SUCCESS = 'GET_RANKING_SUCCESS';
export const GET_RANKING_ERROR = 'GET_RANKING_ERROR';
